Feature bot controller update
Tawkie/tawkie-app pull request #31
Opened 2024-06-25 14:54 UTC by VincePaulin

Initial instructions:

- enum pour _checkLatestMessages et dépendants
- add comments describing functions
- await Matrix sync
- handleSocialNetworkAction use better boolean logic syntax. (not == true)
- social network non nullable bools
- handleConnection better name can be found
- handleNewRoomsSync rm
- reduce delays, listen for events
- getWhatsAppNetwork should be in SocialNetwork (data structure could possibly be revised)

2024-07-08 07:08 UTC, ignyx requested changes
Good improvements ! I requested a few minor changes. We could probably consider refactoring a few of the Networks to their own file, but not right now :+1:

2024-07-08 07:08 UTC, ignyx commented on lib/utils/bridge_utils.dart
> +      !patterns['alreadyLogout']!.hasMatch(message);
This logic is counter intuitive. We are still connected with `not success and not alreadyLoggedIn` ? Perhaps `patterns['success']` could have a better name ?

2024-07-08 07:08 UTC, ignyx commented on lib/utils/bridge_utils.dart
> +bool isDisconnected(String message, Map<String, RegExp> patterns) {
This function is (currently) logically equivalent to `not isStillConnected`. I would recommend deleting this function and using `!isStillConnected` instead of `isDisconnected`.

2024-07-08 07:08 UTC, ignyx commented on lib/utils/bridge_utils.dart
> +RegExpPingPatterns getPingPatterns(String networkName) {
`networkName` could be an enum (requires changes in other files). Minor performance improvements, but mostly better code robustness and readability.

2024-07-08 07:08 UTC, ignyx commented on lib/utils/bridge_utils.dart
> +Map<String, RegExp> getLogoutNetworkPatterns(String networkName) {
possible enum as well

2024-07-08 07:08 UTC, ignyx commented on lib/widgets/matrix.dart
> +      await matrixClient.ensureInitializationComplete();  // Make sure initialization is complete
What is the performance impact of awaiting this sync here ? Have you tried syncing a "large account" for the first time ?

2024-07-08 07:08 UTC, ignyx commented on lib/widgets/matrix_client.dart
> +class MatrixClient {
This comment pertains to the entire file and why it exists. What at you trying to achieve here ? Is creating a class necessary ?

If you do chose to keep the class, maybe reconsider the name : `MatrixClient` is not actually a client class but wraps one. Also, add comments to explain what the class does and how to use it

2024-07-08 07:08 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
> +      if (!await _sendPingMessage(roomBot, socialNetwork)) {
consider moving this to a boolean variable, for example `successSendingPing`

2024-07-08 07:08 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
> +      await Future.delayed(const Duration(seconds: 2));
was there no way to listen for events ?

2024-07-08 07:08 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
> +    }
consider adding a line between debug printing and business logic to improve readability

2024-07-08 07:08 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
>                return 'Connected';
should probably return an enum or boolean instead of a String

2024-07-08 07:08 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
> +        completer.complete("error");
often times you left the error as "error". Could you please be more descriptive ? (here and in other occurences)

2024-07-09 13:35 UTC, VincePaulin commented on lib/widgets/matrix.dart
> +      await matrixClient.ensureInitializationComplete();  // Make sure initialization is complete
Performance doesn't seem to be impacted even when I first log in with my account (I have a lot of conversation to retrieve). But I still made a change to make sure I do this in the background.

2024-07-09 14:46 UTC, VincePaulin commented on lib/pages/add_bridge/add_bridge.dart
> +      await Future.delayed(const Duration(seconds: 2));
I had tried to implement a streamController external to the function, but I couldn't do any better than that.
If you think it's better to try making a StreamController, I can try again.

2024-07-11 06:54 UTC, ignyx approved these changes

2024-07-11 06:54 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
> +    }
Shouldn't errors be thrown rather than returned ?

This comment applies to multiple similar code snippets

2024-07-11 08:45 UTC, ignyx commented on lib/pages/add_bridge/add_bridge.dart
> +  Future<ConnectionStatus> disconnectFromNetwork(BuildContext context,
Do we still need to return a `ConnectionStatus` ? would a `void` be enough ?

2024-07-11 15:47 UTC, ignyx approved these changes
LGTM

2024-07-12 11:52 UTC, merged